# Generated by Django 5.1.7 on 2025-03-25 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_server_name', models.CharField(max_length=255, unique=True)),
                ('db_type', models.CharField(max_length=255)),
                ('engine', models.CharField(max_length=255)),
                ('db_username', models.CharField(max_length=255)),
                ('db_password', models.CharField(max_length=255)),
                ('hostname', models.CharField(max_length=255)),
                ('port', models.CharField(max_length=10)),
            ],
        ),
    ]
