# Generated by Django 5.1.7 on 2025-03-25 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drsti_iot', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tenant',
        ),
    ]
